site_name: TheCodeManual
nav:
  - Home: index.md
  - VsCodeSetup: ./vscode-setup/index.md
  - Windows Command Prompt (CMD) Reference Guide: ./windows-cmd-reference-guide/index.md
  - Linux Command Line Reference Guide: ./linux-command-line-reference-guide/index.md
  - Nix package manager: ./nix-package-manager/index.md
  - HTML5: 
    - The Ultimate HTML Guide: ./html-guide/index.md
    - Introduction & Boilerplate Setup: ./html-guide/setup.md
    - Text Formatting & Headings: ./html-guide/text-formatting.md
    - Links and Navigation: ./html-guide/links.md
    - Images and Media: ./html-guide/media.md
    - Lists and Tables: ./html-guide/lists-tables.md
    - Forms and Input Elements: ./html-guide/forms.md
    - Semantic HTML: ./html-guide/semantic-html.md
    - HTML Meta Tags & SEO Basics: ./html-guide/meta-tags.md
  - CSS3: 
    - The Ultimate CSS3 Guide: ./css-guide/index.md
    - CSS Syntax: ./css-guide/css-syntax.md
    - CSS Selectors: ./css-guide/css-selectors.md

theme: 
  name: material
  palette:
    # Automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preferenceCopied!   